spring:
  application:
    profiles:
      include: common-dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    pool-name: SpringBootHikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/catalog?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=db-catalog&allowPublicKeyRetrieval=true&useSSL=false&charset=utf8
    username: jamie
    password: Hsbc1234
    initialization-mode: always
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      idle-timeout: 30000
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sleuth.sampler.probability: 0.1

swagger.api:
  enabled: true
  title: "Catalog Service"
  description: "Sample Microservice - catalog service for demonstration purpose"
  terms-of-service-url: "https://oauth.net/2"
  version: "v1.0.0"
  controller:
    base-package: "org.akj"
  contact:
    name: "Jamie Zhang"
    email: "akjamie.zhang@outlook.com"