apiVersion: v1
kind: Service
metadata:
  name: config-service-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      nodePort: 30001
      protocol: TCP
  selector:
    app: config-service