kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-config-service
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Mi